### PR TITLE
Change logo image file and some resizing of logo and header

### PR DESCRIPTION
**Pull request by jmb213**
Change logo image file and some resizing of logo and header. Minor text changes.

### CODE REVIEW

**Comment by patrick-miller** [comment]
You will also need to upload the image ```img/2PiBanner.png``` to the static folder for this to work.

https://github.com/jmb213/2pi-financial/tree/master/app/static/img

**Comment by jmb213** [comment]
I will give it a shot now. stay tuned.



________________________________

**Comment by jmb213** [comment]
i pushed the new image file to my git repository and tried to initiate a new pull request. I am not sure if the new pull request went through. Let me know if I need to do anything.


jules



________________________________

**Comment by patrick-miller** [comment]
The nice thing about pull requests is that once they are open, all the subsequent changes you push will automatically get updated in that pull request (so you image addition is auto included here).

I will merge this if you are happy with it.

**Comment by jmb213** [comment]
Go ahead and push in. When Paul (my artist friend who designed the logo) sees it, i am sure there will be some tweeks.


On Mar 8, 2018 11:38 AM, Patrick Miller <notifications@github.com> wrote:

The nice thing about pull requests is that once they are open, all the subsequent changes you push will automatically get updated in that pull request (so you image addition is auto included here).

I will merge this if you are happy with it.

**Pull request merged**
